# 必须包含以下基础配置
title: WorkGen
url: "http://localhost:4000"
baseurl: "/workgen"  # 如果仓库名不是username.github.io则需要此项
environment: production

# 仅使用GitHub Pages支持的插件
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

# 禁用不兼容功能
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

# 禁用本地开发插件
exclude:
  - vendor
  - .github 