name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.6
        bundler-cache: true
    - run: bundle install
    - run: npm run build
    - run: npm run dev & # 后台启动服务器
    - run: npx wait-on http://localhost:4000
    - run: npm run test 