name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    # 设置Ruby环境
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.6'
        bundler-cache: true
        cache-version: 2
    
    # 设置Node.js环境
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'
    
    # 安装依赖
    - run: npm ci
    - run: bundle install
    
    # 构建步骤
    - run: bundle exec jekyll build
    - run: npm run build
    
    # 启动服务并测试
    - name: Start server
      run: |
        echo "Checking _site directory..."
        ls -la _site
        nohup npm run dev > server.log 2>&1 &
        echo "SERVER_PID=$!" >> $GITHUB_ENV
        sleep 20  # 增加等待时间
        echo "4000" > port.txt  # 硬编码端口
        echo "Server logs:"
        cat server.log
    
    - name: Wait for server
      run: |
        PORT=4000
        echo "Waiting for port $PORT..."
        curl --retry 15 --retry-delay 10 --retry-all-errors -v http://localhost:$PORT
        npx wait-on http://localhost:$PORT --timeout 300000
    
    - name: Run tests
      run: |
        PORT=$(cat port.txt)
        echo "Running tests against port $PORT..."
        npm run test -- --config baseUrl=http://localhost:$PORT
    
    - name: Show server logs
      if: always()
      run: cat server.log 