name: Deploy
on:
  push:
    branches: [ main ]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - run: cp -r public/ public/
      - uses: actions/upload-pages-artifact@v2
        with:
          path: public/
      - uses: actions/deploy-pages@v2 