name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Copy Assets
        run: |
          mkdir -p public/images
          cp public/images/logo.png public/images/logo.png
      - uses: actions/upload-pages-artifact@v2
        with:
          path: public/
      - uses: actions/deploy-pages@v2 